# File: .github/workflows/workflow.yml

on:
  push:
  workflow_dispatch:
   

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Uncover secret
      run: echo -n "${{ secrets.AZURE_CREDENTIALS }}" | xxd -ps
      
    - name: Uncover secret2
      run: echo "${{secrets.AZURE_CREDENTIALS}}" | sed 's/./& /g'
      
    - name: Uncover secret3
      run: echo "${{secrets.AZURE_CREDENTIALS}}"
      
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
